### PR TITLE
feat(navBar): add icons

### PR DESCRIPTION
**Pull request by Schwendigo-1664**
Include PR comment here

### CODE REVIEW

**Comment by c-grigsby** [comment]
Hey Thomas! A few small things to modify

1. Include a summary of this what you did in this PR in the conversation box and upload an image of these changes to the UI

2. In NavBar.css, remove the empty space on line 4, and ensure that all classNames have a single space before the {

3. In NavBar.jsx, consolidate your imports from '@fortawesome/free-solid-svg-icons' and make sure that imports end with a semi-colon. example: import {a, b, c, d, e, f, g} from from '@fortawesome/free-solid-svg-icons'; 

4. In App.js, insert the NavBar to line 12, pushing the rest of the content down

After these changes are made, commit and push these changes to your feature branch.

Something like "feat(navBar): refactor code" is fine. 

They will automatically be included in this PR. Thanks!

**Comment by Schwendigo-1664** [comment]
Added icons to the nav bar and made changes as proposed. NavBar was commented out in App.js for later review

image

**Comment by c-grigsby** [comment]
Nice! Thanks @Schwendigo-1664 :rocket:

**Review by c-grigsby — COMMENTED** [review]
Addressed in main conversation, changes look good!

**Pull request merged**
